### ISSUE TITLE
Kan ikke tilgå panelet.

### ISSUE THREAD

**Issue by ELT-SadikReis** [MikkelDK/ELT#12]
Jeg prøvede at lave en csgo server da vi skal have en og jeg gjorde som du havde skrevet den der guide der men efter et par min kunne jeg ikke tilgå panelet længere ved ikke om det bare er et crash eller lige hvad det er selve gameservers er oppe stadig. :)

**Comment by MikkelDK** [comment]
Disken var fyldt op.

Prøv og lav en ny igen! ;)
